<script lang="ts">
	import {
		Folder,
		Star,
		Clock,
		BookOpen,
		Palette,
		Type,
		Code,
		Image as ImageIcon,
		ChefHat,
		LayoutGrid,
		Sparkles,
		Link2,
		FileText,
		Video,
		Music,
		Map,
		Utensils,
		Briefcase,
		GraduationCap,
		Heart,
		Camera,
		PenTool,
		Rocket,
		Library,
		Globe,
		Zap,
		Search,
		Settings,
		Plus,
		X,
		Trash2,
		Download,
		FolderOpen,
		Upload,
		Wand2,
		ScanText,
		Copy,
		ExternalLink,
		Eye,
		EyeOff,
		ChevronRight,
		ChevronDown,
		MoreHorizontal,
		Pencil,
		Check,
		Command,
		ImagePlus,
		Scissors,
		StickyNote,
		Shield,
		Layers,
		RefreshCw,
		Clipboard,
		ChevronLeft,
		FilePlus,
		FolderPlus,
		File
	} from '@lucide/svelte';

	let { name = 'folder', size = 16, ...rest } = $props();

	const map: Record<string, any> = {
		folder: Folder,
		'folder-open': FolderOpen,
		star: Star,
		clock: Clock,
		'book-open': BookOpen,
		palette: Palette,
		type: Type,
		code: Code,
		image: ImageIcon,
		'chef-hat': ChefHat,
		'layout-grid': LayoutGrid,
		sparkles: Sparkles,
		link: Link2,
		'file-text': FileText,
		video: Video,
		music: Music,
		map: Map,
		utensils: Utensils,
		briefcase: Briefcase,
		'graduation-cap': GraduationCap,
		heart: Heart,
		camera: Camera,
		'pen-tool': PenTool,
		rocket: Rocket,
		library: Library,
		globe: Globe,
		zap: Zap,
		search: Search,
		settings: Settings,
		plus: Plus,
		x: X,
		'trash-2': Trash2,
		download: Download,
		upload: Upload,
		'wand-2': Wand2,
		'scan-text': ScanText,
		copy: Copy,
		'external-link': ExternalLink,
		eye: Eye,
		'eye-off': EyeOff,
		'chevron-right': ChevronRight,
		'chevron-down': ChevronDown,
		'more-horizontal': MoreHorizontal,
		pencil: Pencil,
		check: Check,
		command: Command,
		'image-plus': ImagePlus,
		scissors: Scissors,
		'sticky-note': StickyNote,
		shield: Shield,
		layers: Layers,
		refresh: RefreshCw,
		clipboard: Clipboard,
		'chevron-left': ChevronLeft,
		'file-plus': FilePlus,
		'folder-plus': FolderPlus,
		file: File
	};

	const Cmp = $derived(map[name] ?? Folder);
</script>

<Cmp {size} {...rest} />
